### PR TITLE
Handle positions for .sbt files.

### PR DESCRIPTION
**Pull request by olafurpg**
Supersedes #6

### CODE REVIEW

**Comment by olafurpg** [comment]
I'm not sure what is causing the resolution errors. I am unable to reproduce locally.

**Review by jvican — APPROVED** [review]
LGTM, good work!

**Comment by olafurpg** [comment]
Bintray seems up http://status.bintray.com/

**Comment by olafurpg** [comment]
Thanks to @martinduhem's help, I was able to fix the resolution error. We were missing a resolver on Typesafe releases. CI is green, let's merge!

**Pull request merged**
